`timescale 1ns/1ns

// imports for communication with the agent through the C++ wrapper
import "DPI-C" context function void init_agent();
import "DPI-C" context function void get_new_constraints(input real prev_x[4], input real delta_cov, output real next_x[4]);
import "DPI-C" context function void cleanup_agent();

class Request;
    rand logic [2:0] ReqModule; 
    rand int NCycles; 
    // added all design inputs to the class Request
    rand logic [2:0] DoneModule;
    rand logic RstSignal;
    
    // probabilities generated by the agent (0.0 to 1.0)
    real p_req_m1, p_req_m2, p_req_m3, p_N;
    
    // weights for sv dist constraints
    int w1_1, w1_0, w2_1, w2_0, w3_1, w3_0;
    int target_N; 

    logic [2:0] prev_req;

    // convert the agent's floating-point probabilities into integer weights for sv
    function void pre_randomize();
        w1_1 = int'(p_req_m1 * 100.0); w1_0 = 100 - w1_1;
        w2_1 = int'(p_req_m2 * 100.0); w2_0 = 100 - w2_1;
        w3_1 = int'(p_req_m3 * 100.0); w3_0 = 100 - w3_1;
        
        // map the agent's 0.0-1.0 cycle to 1-10 clock cycles
        target_N = int'(p_N * 9.0) + 1; 
    endfunction

    // Apply the agent-driven distributions to the request modules
    constraint req_c {
        ReqModule[0] dist {1 := w1_1, 0 := w1_0};
        ReqModule[1] dist {1 := w2_1, 0 := w2_0};
        ReqModule[2] dist {1 := w3_1, 0 := w3_0};
    }
     
    // lock the number of cycles to the agent's output
    constraint n_c {
        NCycles inside {[1:10]};
        NCycles == target_N;
    }

    // keep reset low during active testing for nb_interrupts
    constraint rst_c {
        RstSignal == 0; 
    }
    
    // use a static distribution for Done signals 
    constraint done_c {
        DoneModule dist {3'b000 := 80, 3'b001 := 5, 3'b010 := 5, 3'b100 := 10};
    }
endclass

module tb();
    // file handle for the per-test coverage report since the tb module is only run once by the agent
    int cov_file; 

    logic [2:0] req; 
    logic [2:0] done;
    logic clk, rst;
    int nb_interrupts;
    logic [4:0] mstate;
    logic [1:0] accmodule;

    // Simulation Parameters 
    parameter int N = 10;   // number of requests per test batch
    parameter int M = 50; // max total requests allowed
    int num_tests;          // total tests (M/N)
    
    // agent tracking variables
    real current_cov, last_cov, delta_cov;
    real current_constraints[4]; // current policy [p_m1, p_m2, p_m3, p_N]
    real next_constraints[4];    // next policy predicted by the agent

    controller iDUT(.clk(clk), .reset(rst), .req(req), .done(done), .mstate(mstate), .accmodule(accmodule), .nb_interrupts(nb_interrupts) );

    // clock generation
    parameter PERIOD = 20;
    initial clk = 0;
    always #(PERIOD/2) clk = ~clk;

    // FUNCTIONAL COVERAGE MODEL:
    
    // M1 has the highest priority, so if it requests the memory, it should get it the next cycle
    covergroup cg_M1_highest_priority @(posedge clk iff !rst);
        cp_M1_req: coverpoint req[0] { bins M1_req = {1'b1}; }
        cp_M1_next: coverpoint iDUT.ns { bins M1_next = {8'b00000010, 8'b00000100}; } 
        cross_M1_req_and_next: cross cp_M1_req, cp_M1_next;
    endgroup
    
    // M1 has the ability to interrupt M2
    covergroup cg_M1_interrupt_M2 @(posedge clk iff !rst);
        cp_M1_req: coverpoint req[0] { bins M1_req = {1'b1}; }
        cp_M1_next: coverpoint iDUT.ns { bins M1_next = {8'b00000010, 8'b00000100}; } 
        cp_M2_has_mem: coverpoint iDUT.ps { bins M2_has_mem = {8'b00010000, 8'b00100000}; }
        cp_M2_not_done: coverpoint req[1] { bins M2_not_done = {1'b0}; }
        cross_M1_interrupt_M2: cross cp_M1_req, cp_M1_next, cp_M2_has_mem, cp_M2_not_done;
    endgroup 
    
    // M1 has the ability to interrupt M3
    covergroup cg_M1_interrupt_M3 @(posedge clk iff !rst);
        cp_M1_req: coverpoint req[0] { bins M1_req = {1'b1}; }
        cp_M1_next: coverpoint iDUT.ns { bins M1_next = {8'b00000010, 8'b00000100}; } 
        cp_M3_has_mem: coverpoint iDUT.ps { bins M3_has_mem = {8'b01000000, 8'b10000000}; }
        cp_M3_not_done: coverpoint req[2] { bins M3_not_done = {1'b0}; }
        cross_M1_interrupt_M3: cross cp_M1_req, cp_M1_next, cp_M3_has_mem, cp_M3_not_done;
    endgroup 
    
    // when M1 has the memory, it holds it indefinitely until it asserts its done signal
    covergroup cg_M1_indef_uninterrupted @(posedge clk iff !rst);
        cp_M1_has_mem_indef: coverpoint iDUT.ps { bins M1_indef = {8'b00000010}; }
        cp_M1_not_done: coverpoint done[0] { bins M1_not_done = {1'b0}; }
        cross_M1_indef_uninterrupted: cross cp_M1_has_mem_indef, cp_M1_not_done;
    endgroup
    
    // want to see the different values of the interrupt count 
    // [5:$] used due to limited number of inputs per test
    covergroup cg_interrupt_stress @(posedge clk iff !rst);
        cp_high_interrupts: coverpoint nb_interrupts { 
            bins int_1 = {1};
            bins int_2 = {2};
            bins int_3 = {3};
            bins int_4 = {4};
            bins high_count = {[5:$]}; 
        }
    endgroup
    
    // M2 and M3 tie when they both request access and the memory isn't currently being held
    covergroup cg_M2_M3_tie @(posedge clk iff !rst);
        cp_both_req: coverpoint req { bins tie_condition = {3'b110}; }
        cp_in_idle: coverpoint iDUT.ps { bins idle_state = {8'b00000001}; }
        cross_tie: cross cp_both_req, cp_in_idle;
    endgroup
    
    // covergroup to increase teh code coverage of the agent since it rarely hit this bin
    covergroup cg_M3_early_done @(posedge clk iff !rst);
        cp_M3_C1: coverpoint iDUT.ps { bins m3_c1 = {8'b01000000}; }
        cp_M3_done: coverpoint done[2] { bins done_high = {1'b1}; }
        cross_early_done: cross cp_M3_C1, cp_M3_done;
    endgroup
    
    // instantiate covergroups
    cg_M1_highest_priority cg_inst_M1_highest_priority = new;
    cg_M1_interrupt_M2 cg_inst_M1_interrupt_M2 = new;
    cg_M1_interrupt_M3 cg_inst_M1_interrupt_M3 = new;
    cg_M1_indef_uninterrupted cg_inst_M1_indef_uninterrupted = new;
    cg_interrupt_stress cg_inst_interrupt_stress = new;
    cg_M2_M3_tie cg_inst_M2_M3_tie = new;
    cg_M3_early_done cg_inst_M3_early_done = new;

    // runtime variables
    Request req_obj;
    int start_interrupts;
    int batch_interrupts;
    real agent_reward;
    
    // varaibles to reward hard to hit cases
    bit hit_m1_interrupt;
    bit hit_tie;

    initial begin
        // setup the per test coverage output report file 
        cov_file = $fopen("per_test_coverage_report.txt", "w");
        if (cov_file == 0) begin
            $display("ERROR: Could not open coverage report file.");
            $finish;
        end

        // ensure we run at least 1 test (even if N=M=1)
        num_tests = (M >= N) ? (M / N) : 1;
        $display("Config: N=%0d, M=%0d. Running %0d test(s).", N, M, num_tests);

        // boot up agent
        init_agent(); 
        req_obj = new();
        
        // nitial neutral policy for agent
        current_constraints = '{0.5, 0.5, 0.5, 0.5};
        last_cov = 0.0;
        done = 3'b000;

        // apply reset 
        rst = 1; req = 3'b000;
        #(PERIOD * 2) rst = 0;

        // iterate through num_tests (M/N)
        for (int test_idx = 0; test_idx < num_tests; test_idx++) begin
            start_interrupts = nb_interrupts;
            hit_m1_interrupt = 0;
            hit_tie = 0;

            // apply agent's predicted policy to the request class
            req_obj.p_req_m1 = current_constraints[0];
            req_obj.p_req_m2 = current_constraints[1];
            req_obj.p_req_m3 = current_constraints[2];
            req_obj.p_N      = current_constraints[3]; 

            // execute N requests for the current policy
            for (int r = 0; r < N; r++) begin
                req_obj.prev_req = req; 
                
                // randomize based on the agent's constraints
                if (!req_obj.randomize()) $fatal(1, "Randomization failed!");
                
                // drive the signals to the DUT
                req  = req_obj.ReqModule;
                done = req_obj.DoneModule;
                rst  = req_obj.RstSignal; 
                
                // hold the request for NCycles
                for (int cyc = 0; cyc < req_obj.NCycles; cyc++) begin
                    @(posedge clk);
                    // sample all coverage points
                    cg_inst_M1_highest_priority.sample();
                    cg_inst_M1_interrupt_M2.sample();
                    cg_inst_M1_interrupt_M3.sample();
                    cg_inst_M1_indef_uninterrupted.sample();
                    cg_inst_interrupt_stress.sample();
                    cg_inst_M2_M3_tie.sample();
                    cg_inst_M3_early_done.sample();

                    // check if edge cases were hit to provide agent with extra reward
                    // NOTE: these edge cases were found during initial testing 
                    // M1 interrupts M2 or M3
                    if ((iDUT.ps == 8'b00010000 || iDUT.ps == 8'b00100000 || 
                         iDUT.ps == 8'b01000000 || iDUT.ps == 8'b10000000) && req[0]) begin
                        hit_m1_interrupt = 1;
                    end
                    // M2/M3 tie happens while in IDLE
                    if (iDUT.ps == 8'b00000001 && req == 3'b110) begin
                        hit_tie = 1;
                    end
                end
            end
        
            batch_interrupts = nb_interrupts - start_interrupts;
            
            // calculate the coverage delta
            current_cov = $get_coverage();
            delta_cov = current_cov - last_cov;
            last_cov = current_cov;

            // base reward is tied directly to discovering new coverage
            agent_reward = (delta_cov * 100.0);

            // add bonus reward for finding edge cases
            if (hit_m1_interrupt) begin
                agent_reward += 50.0; 
            end
            if (hit_tie) begin
                agent_reward += 100.0; // big bonus since its hard to reach
            end
            
            // log results to the console and write to the per-test coverage text file
            $display("[Test %0d] Cov: %0.2f%% (+%0.2f%%) | Reward: %0.2f", test_idx+1, current_cov, delta_cov, agent_reward);
            $fdisplay(cov_file, "Test: %0d | Coverage: %0.2f%%", test_idx+1, current_cov);
            
            // send the previous constraints and the resulting reward to the agent to get values for the next run
            get_new_constraints(current_constraints, agent_reward, next_constraints);
            current_constraints = next_constraints; // Update policy for the next loop
            
            // stop once 100% coverage is hit
            if (current_cov >= 100.0) begin
                $display("100%% Functional Coverage Achieved at Test %0d! Stopping agent.", test_idx+1);
                break;
            end
        end
        
        // close and clean up the agent
        cleanup_agent();
        
        // finished making the per test coverage report
        if (cov_file) begin
            $fclose(cov_file);
        end
        $stop;
    end

    // dump waveforms for debugging
    initial begin
        $dumpfile("test.vcd");
        $dumpvars(0, tb);
    end
endmodule
